paths:
  config: "./data/config"
  database: "./data/db"
  modules: "./data/modules"
  themes: "./data/themes"

http_server:
  enable_server: true
  http_address: "0.0.0.0"
  http_port: 8000
# http_max_connections: 1000
# http_max_requests: 50000
# http_workers: 10
  http_pid: "./data/server/stilus.pid"
  http_log: "./data/server/stilus.log"

development:
  web_server:
    host: "0.0.0.0"
    port: 8090
  build:
    dir: "./dist"
    css_source_map: true
    pages:
      index: # Index page
        entry: "src/Stilus.js" # Entry script for the page
        template: "public/index.html" # Html template files
        filename: "index.html" # Output file: ./dist/index.html




