version: '3'
services:

  stilus_api:
    working_dir: /app
    build:
      context: ./docker/api
    volumes:
      - ".:/app"
    expose:
      - "8080"
    ports:
      - "8080:8080"

  stilus_web:
    working_dir: /app
    build:
      context: ./docker/web
    volumes:
      - ".:/app"
    expose:
      - "8888"
    ports:
      - "8888:8888"
